#Use an official Python runtime as a parent image
FROM ubuntu:latest


# Set the working directory in the container to /app
WORKDIR /app


# Copy the current directory contents into the container at /app
COPY . /app 

# Install any needed packages specified in requirements.txt
RUN apt-get update && apt-get install -y python3 python3-pip

#Set environment variables
ENV NAME World

#Default command to run when starting the container
CMD ["python3", "app.py"]